# Generated by Django 3.2.3 on 2021-05-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phoneNo', models.IntegerField()),
                ('status', models.CharField(choices=[('Safe', 'Safe'), ('Vaccinated', 'Vaccinated'), ('Vulnerable', 'Vulnerable'), ('Covid Positive', 'Covid Positive'), ('Recovered', 'Recovered')], max_length=100)),
            ],
        ),
    ]
