# Generated by Django 3.2.3 on 2021-05-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='ip',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
