# Generated by Django 3.2.3 on 2021-05-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210523_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
